current-version:
	$(Q) if [ -f ".version" ]; then \
		cat .version;               \
	elif [ -d ".git" ]; then        \
		git describe --always;      \
	else                            \
		echo "unknown";             \
	fi

