##
## MBSL Clean Makefile
##

distclean-init:
distclean-body:
distclean-fini:

kernel-distclean = $(TOOLCHAIN_ENV) $(MAKE) -C $(KERNEL_PATH) ARCH=microblaze distclean
common-distclean = $(TOOLCHAIN_ENV) $(MAKE) -C $($(1)_PATH) distclean
