#!/bin/sh

/bin/echo "Starting rcS..."

/bin/echo "++ Creating device points"
/bin/mkdir /dev/pts
/bin/mount -t devpts devpts /dev/pts

/bin/echo "++ Mounting filesystem"
/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys
/bin/mount -t tmpfs none /tmp

/bin/echo "++ Loading system loggers"
/sbin/syslogd
/sbin/klogd

/bin/echo "++ Starting telnet daemon"
/usr/sbin/telnetd -l /bin/sh
#/usr/sbin/httpd
#/usr/sbin/ntpd
#/usr/sbin/inetd

/bin/echo "rcS Complete"
